apply plugin: 'com.android.application'

// Load keystore.properties
def keystorePropertiesFile = rootProject.file("app/keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 37 //'android-S'
	signingConfigs {
		release {
			storeFile file(keystoreProperties['storeFile'])
			storePassword keystoreProperties['storePassword']
			keyAlias keystoreProperties['keyAlias']
			keyPassword keystoreProperties['keyPassword']
		}
	}
	defaultConfig {
		applicationId "com.maknoon.audiocataloger"
		minSdk 21
		targetSdk 37
		versionCode 35
		versionName "20"
		signingConfig signingConfigs.release
		vectorDrawables.useSupportLibrary = true
	}
	buildTypes {
		release {
			shrinkResources true
			minifyEnabled true
			signingConfig signingConfigs.release
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
		debug {
			//signingConfig signingConfigs.release
			//minifyEnabled true
		}
	}
	buildFeatures {
		buildConfig = true
	}
    namespace 'com.maknoon.audiocataloger'
}

repositories {
	google()
	mavenCentral()
}

dependencies {
	implementation 'com.google.android.material:material:1.14.0-alpha10'
	implementation 'androidx.appcompat:appcompat:1.7.1'
	implementation 'androidx.media3:media3-exoplayer:1.10.0'
	implementation 'androidx.media3:media3-ui:1.10.0'
	implementation 'androidx.media3:media3-session:1.10.0'
	implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
}
